### ISSUE TITLE
Unable to login with given credentials

### ISSUE THREAD

**Issue by Mazzzy** [ccwukong/ElfCommerce#48]
I put username : test@test.com and password: 123 (as mentioned in doc)
Gives authentication error : Invalid email or password.
API response shows : No account found error.

Can someone help on this?

**Comment by ccwukong** [comment]
Hi @Mazzzy,

My bad, I was testing changing password function and forgot to change it back.

It shld be working now.

Meanwhile, I'm working on the installation script to reset demo account password periodically, suggested that you should create a test account for yourself in case someone else changes the demo account password again.

Happy hacking:)

NC

**Comment by Mazzzy** [comment]
Thanks for the update.

cheers!
