### ISSUE TITLE
Login Credentials don't work

### ISSUE THREAD

**Issue by BenjaminHoppe** [ccwukong/ElfCommerce#51]
Hey, trying to use provided test credentials and they seem to be invalid.

**Comment by ccwukong** [comment]
> Hey, trying to use provided test credentials and they seem to be invalid.

Hi @BenjaminHoppe 
I tested it locally and it worked.

- Make sure you restore the database by using **db.sql** file under **/server/db/** directory
- Make sure you have a record with email account **'test@test.com'** in the **user** table(The record should be inserted while restoring the database)
- Make sure you updated the database configurations using your own DB credentials, you can find the config file here **/server/.env** in the following format:
```
tokenSecret=ANY_LONG_STRING
dbHost=localhost
dbUser=YOUR_DB_USER
dbPassword=YOUR_DB_PASSWORD
dbName=YOUR_DB_NAME
testDbName=YOUR_TEST_DB_NAME
sendgridApiKey=YOUR_SENDGRID_API_KEY
sendgridDailyLimit=100
elasticemailApiKey=YOUR_ELASTIC_EMAIL_API_KEY
elasticemailDailyLimit=100
passwordCallbackUrl=https://www.example.com
senderEmail=YOUR_SUPPORT_EMAIL_ACCOUNT
```
