### ISSUE TITLE
Cloned and application test user login has been configured - Login shows invalid username or password

### ISSUE THREAD

**Issue by pradeepkalkunte** [ccwukong/ElfCommerce#63]
Hi, Cloned the Github source code and after that application setup with compilation. The application test user login (test@test.com) has been configured - Login shows invalid username or password. The DB recovery has been done with the db.sql and the user record inserted into the user table.

Now the application login opens as expected but does not allow password change or login. Only the JS validation for incorrect email or password works.

Any ideas where we are going wrong? our env file herewith.

tokensecret=REPLACE_THIS_WITH_ANY_LONG_RANDOM_STRING
dbHost=172.31.4.41
dbUser=application
dbPassword=application
dbName=Ecommerce
testDbName=Ecommerce
sendgridApiKey=SENDGRID_API_KEY
sendgridDailyLimit=SENDGRID_DAILY_LIMIT_FOR_FREETIER
elasticemailApiKey=ELASTICEMAIL_API_KEY
elasticemailDailyLimit=ELASTICEMAIL_DAILY_LIMIT_FOR_FREETIER
passwordCallbackUrl=https://www.example.com
senderEmail=xxxxxxxxxxx@gmail.com

Thank you

**Comment by ccwukong** [comment]
Hi @pradeepkalkunte, I'm working on restructuring the project and making configuration easier. I'm aiming to finish it in 2~3 wks, pls check back later and apologies for the inconvenience.

**Comment by pradeepkalkunte** [comment]
Thank you for your update.
